language: ruby
rvm:
  - 2.1
  - 2.2
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y liblapack-dev
# for ATLAS implementation of LAPACK one can use;
#  - sudo apt-get install -y libatlas-base-dev 
install:
  - gem install bundler
  - bundle install
  - bundle exec rake install
script: 
  - bundle exec rspec spec
