# Site settings
title: spitzy
email: #alexej.go@googlemail.com
description: > # this means to ignore newlines until "baseurl:"
  Solve differential equations in Ruby
baseurl: "/spitzy" # the subpath of your site, e.g. /blog/
url: #"http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: #jekyllrb
github_username:  agisga

# Build settings
# markdown: kramdown

markdown: redcarpet
highlighter: pygments
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.1.0
  #
# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
    
# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
